fix: removing tar strip-components flag
Signed-off-by: michael <mxnxpx@gmail.com>

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -17,10 +17,10 @@ release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 # debug
-echo "untarring download"
+echo "untarring download $release_file"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
 # debug
 sleep 60 
